spring:
  application:
    name: kaimono-catalog-service

kaimono:
  faker:
    enabled: true
    data:
      min-price: 5
      max-price: 50
      amount: 100

server:
  port: 9001
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5
