apiVersion: apps/v1
kind: Deployment
metadata:
  name: kaimono-catalog-service
  labels:
    app: kaimono-catalog-service
spec:
  selector:
    matchLabels:
      app: kaimono-catalog-service
  template:
    metadata:
      labels:
        app: kaimono-catalog-service
    spec:
      containers:
        - name: kaimono-catalog-service
          image: kaimono-catalog-service
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          ports:
            - containerPort: 9001
          env:
            - name: BPL_JVM_THREAD_COUNT
              value: "50"
            - name: SPRING_FLYWAY_URL
              value: jdbc:postgresql://kaimono-postgres/kaimonodb_catalog
            - name: SPRING_R2DBC_URL
              value: r2dbc:postgresql://kaimono-postgres/kaimonodb_catalog
